#!/usr/bin/env node
// Writes src/version.ts from package.json.version so the runtime version
// reported in the User-Agent header always matches the stamped package version.
//
// Called automatically via the "prebuild" npm lifecycle script, which runs
// before "build" (tsc). The release workflows run:
//   npm version --no-git-tag-version <semver>   ← stamps package.json
//   npm run build                                ← triggers prebuild first
// ...so the compiled binary always reflects the actual published version.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

const root = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(root, '..', 'package.json'), 'utf8'));
const { version } = pkg;

const out = join(root, '..', 'src', 'version.ts');
const content = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit by hand.
// Run \`npm run build\` (or \`npm run generate:version\`) to regenerate.
export const VERSION = '${version}';
`;

writeFileSync(out, content, 'utf8');
console.log(`generate-version: wrote src/version.ts → ${version}`);
